version: '3.8'

services:
  nginx: # Used for routing traffic to the application
    depends_on:
      - api 
      - client
    restart: always
    build:
      dockerfile: Dockerfile # Relative path to the Dockerfile
      context: ./nginx # Relative path to the context directory (This is for Machines)
    ports:
      - "8000:80"

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
      